### ISSUE TITLE
Binary 1.3 JAR is not downloadable

### ISSUE THREAD

**Issue by shaktimaan** [corley-archive/aws-ant-task#5]
Hi, 
could someone please reup the 1.3 jar file...
I got the 1.2 file running, but it seems to miss a few functions.
i´m a total noob an can´t get the 1.3  compiled :(

**Comment by wdalmut** [comment]
Hi,

I upload the new release and removed the not working link. Consider to use `aws-ant-tasks-0.3-SNAPSHOT-bin.tar.gz` the contain all dependencies or if you have any dependency problem use the `.jar` that not include the package dependencies.
