### ISSUE TITLE
secret security?

### ISSUE THREAD

**Issue by jedierikb** [corley-archive/aws-ant-task#8]
Maybe this is not the right place for this question, and if so, please close this ticket.

I am wondering if there is a protocol for keeping AWS secret, well, secret from other people when using this ANT task?  Imagine: we have a team of people making uploads, but do not want to give everyone a copy of the secret.  What would you suggest?  Thanks!

**Comment by wdalmut** [comment]
Hi, with ANT you can create properties file and import this property files. Of course you can create skeleton of properties without any secret information and you commit this empty skeleton in your remote repository. In this way your developers can easly craete a valid conf file and fill with credentials.

I've created a gist for you https://gist.github.com/3988702

As you can see the .gitignore file force that the build.properties file never goes to git repository. The build.properties.dist is the base used by you and your developers for create the build.properties and fill with real credentials.
