### ISSUE TITLE
contentEncoding attribute?

### ISSUE THREAD

**Issue by jedierikb** [corley-archive/aws-ant-task#9]
Would be helpful to add a contentEncoding attribute for uploading to s3.

This would make it easy to upload gzipped javascript [ see http://stackoverflow.com/a/5447158/62255 ]

**Comment by wdalmut** [comment]
Yeah, you're right actually you can't set the content-encoding attribute. I'll add this feature as soon as possible I hope before this week end.

I think to add a properties that works in the same way of contenttype.

Stay tuned. ;)

**Comment by jedierikb** [comment]
I don't need any of the others listed here:
![aws keys](http://www.freeimagehosting.net/newuploads/pj2un.png)

But I can imagine they might be helpful to include as AWS suggests them as the default options on their S3 Management Console.

**Comment by wdalmut** [comment]
Content-Encoding support added see #10 

We have to work on some refactors before adding other metdata information.
